export const CALENDAR_ADD_REMINDER = 'CALENDAR_ADD_REMINDER';
export const CALENDAR_DELETE_REMINDER = 'CALENDAR_DELETE_REMINDER';
export const CALENDAR_EDIT_REMINDER = 'CALENDAR_EDIT_REMINDER';
export const CALENDAR_UPDATE_DAY = 'CALENDAR_UPDATE_DAY';
export const CALENDAR_UPDATE_MONTH = 'CALENDAR_UPDATE_MONTH';
export const CALENDAR_UPDATE_YEAR = 'CALENDAR_UPDATE_YEAR';
